import { useMemo, useState } from "react";
import { Check, Circle, RotateCcw, X } from "lucide-react";
import SkillTrainerShell, { MistakeCausePrompt, ResultsCard, ReviewMistakesButton, TrainerLoading, TrainerProgress } from "../components/skillTrainers/SkillTrainerShell";
import { useSkillTrainerRun } from "../components/skillTrainers/useSkillTrainerRun";
import { RESULTS_SUMMARY } from "../components/skillTrainers/resultsSummary";
import { CONSTRAINT_PUZZLES, type ConstraintPuzzle } from "../data/skillTrainerQuestions";
import {saveSkillAttempt} from "../lib/skillTrainerProgress";
import {useSkillTrainerRunLog} from "../hooks/useSkillTrainerRunLog";
const DESCRIPTION="Construct an arrangement yourself. Any solution that satisfies every rule is accepted, so you learn to manage constraints rather than recognise a prepared answer.";

export default function DmConstraintBuilderPage(){
 const run=useSkillTrainerRun("dm_constraints",CONSTRAINT_PUZZLES,6);
 if(!run.items)return <SkillTrainerShell title="DM Constraint Builder" description={DESCRIPTION} path="/ucat-dm-constraint-builder" hubPath="/ucat-decision-making-practice" hubLabel="Decision Making" faqKey="dmConstraintBuilder"><TrainerLoading/></SkillTrainerShell>;
 return <ConstraintRun key={run.runKey} puzzles={run.items} sessionId={run.sessionId} reviewMode={run.reviewMode} userId={run.userId} markAnswered={run.markAnswered} restart={run.restart}/>;
}

function ConstraintRun({puzzles,sessionId,reviewMode,userId,markAnswered,restart}:{puzzles:ConstraintPuzzle[];sessionId:string;reviewMode:boolean;userId:string|null;markAnswered:()=>void;restart:(review?:boolean)=>void}){
 const[startedAt,setStartedAt]=useState(()=>Date.now()); const logRun=useSkillTrainerRunLog("dm_constraints",sessionId);
 const[index,setIndex]=useState(0),[placed,setPlaced]=useState<(string|null)[]>(()=>Array(puzzles[0].slots.length).fill(null)),[selected,setSelected]=useState<string|null>(null),[checked,setChecked]=useState(false),[score,setScore]=useState(0),[done,setDone]=useState(false); // True once a wrong check has shown the example: later retries of this puzzle are practice only (no point, no extra saved attempt).
 const[revealed,setRevealed]=useState(false); const p=puzzles[index];
 const positions=useMemo(()=>Object.fromEntries(placed.flatMap((name,i)=>name?[[name,i]]:[])),[placed]); const statuses=p.rules.map(r=>r.check(positions)); const complete=placed.every(Boolean), valid=complete&&statuses.every(Boolean);
 const place=(slot:number)=>{if(checked||!selected)return;setPlaced(old=>{const next=old.map(x=>x===selected?null:x);next[slot]=selected;return next});setSelected(null)};
 const clear=()=>{setPlaced(Array(p.slots.length).fill(null));setSelected(null);setChecked(false)};
 if(done)return <SkillTrainerShell title="DM Constraint Builder" description={DESCRIPTION} path="/ucat-dm-constraint-builder" hubPath="/ucat-decision-making-practice" hubLabel="Decision Making" faqKey="dmConstraintBuilder"><ResultsCard score={score} total={puzzles.length} summary={RESULTS_SUMMARY.dm_constraints} onRestart={()=>restart()} actions={<ReviewMistakesButton trainerType="dm_constraints" userId={userId} onReview={()=>restart(true)}/>}/></SkillTrainerShell>;
 return <SkillTrainerShell title="DM Constraint Builder" description={DESCRIPTION} path="/ucat-dm-constraint-builder" hubPath="/ucat-decision-making-practice" hubLabel="Decision Making" faqKey="dmConstraintBuilder"><TrainerProgress current={index} total={puzzles.length} score={score}/><section className="rounded-2xl border border-border bg-card p-5 shadow-card sm:p-7"><h2 className="text-xl font-semibold">{p.title}</h2><p className="mt-1 text-sm text-muted-foreground">{p.context} Select a name, then choose a slot.</p>
 <div className="mt-5"><h3 className="text-sm font-semibold">Available items</h3><div className="mt-2 flex flex-wrap gap-2">{p.entities.map(name=><button key={name} type="button" disabled={checked} aria-pressed={selected===name} onClick={()=>setSelected(name)} className={`min-h-11 rounded-lg border px-4 py-2 text-sm font-medium ${selected===name?"border-primary bg-primary text-primary-foreground":"border-border bg-background hover:bg-secondary"}`}>{name}</button>)}</div></div>
 <div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{p.slots.map((slot,i)=><button type="button" key={slot} disabled={checked} onClick={()=>place(i)} className="min-h-20 rounded-xl border border-dashed border-border bg-secondary/40 p-3 text-left hover:border-primary"><span className="block text-xs font-semibold uppercase tracking-wide text-muted-foreground">{slot}</span><span className="mt-1 block text-base font-semibold text-foreground">{placed[i]??"Choose item"}</span></button>)}</div>
 <div className="mt-5 rounded-xl border border-border p-4"><h3 className="font-semibold">Rule checker</h3><ul className="mt-3 space-y-2">{p.rules.map((rule,i)=>{const state=statuses[i];return <li key={rule.id} className="flex items-start gap-2 text-sm">{state===true?<Check className="mt-0.5 h-4 w-4 shrink-0 text-green-600" aria-hidden/>:state===false?<X className="mt-0.5 h-4 w-4 shrink-0 text-red-600" aria-hidden/>:<Circle className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" aria-hidden/>}<span className={`min-w-0 flex-1 ${state===false?"text-red-700":"text-foreground"}`}>{rule.text}</span><span className={`shrink-0 text-xs font-semibold leading-5 ${state===true?"text-green-700":state===false?"text-red-700":"text-muted-foreground"}`}>{state===true?"Met":state===false?"Broken":"Not yet decided"}</span></li>})}</ul></div>
 {checked&&<div className={`mt-5 rounded-xl border p-4 ${valid?"border-green-300 bg-green-50":"border-amber-300 bg-amber-50"}`} role="status"><p className="font-semibold">{valid?"Valid arrangement":"Some rules are still broken"}</p><p className="mt-1 text-sm">{valid?(revealed?"You built a valid solution. No point is awarded because the example arrangement was shown.":"You built a solution that satisfies every constraint."):`One valid arrangement is: ${p.exampleSolution.join(" → ")}. Reset and build it, or find another valid solution.`}</p></div>}{checked&&(valid?1:0)<1&&<MistakeCausePrompt key={p.id} trainerType="dm_constraints" sessionId={sessionId} itemId={p.id} userId={userId}/>}
 <div className="mt-5 flex flex-wrap justify-between gap-3"><button type="button" onClick={clear} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-border px-4 py-2 font-medium hover:bg-secondary"><RotateCcw className="h-4 w-4"/>Reset board</button><button type="button" disabled={!complete} onClick={()=>{if(!checked){if(!revealed){markAnswered();void saveSkillAttempt("dm_constraints",{clientSessionId:sessionId,review:reviewMode,itemId:p.id,score:valid?1:0,max:1,seconds:Math.round((Date.now()-startedAt)/1000),at:new Date().toISOString(),components:{constraints:valid}},userId);logRun({correct:score+(valid?1:0),total:index+1,completed:index===puzzles.length-1});if(valid)setScore(s=>s+1);else setRevealed(true)}setChecked(true);return}if(!valid){clear();return}if(index===puzzles.length-1)setDone(true);else{const ni=index+1;setIndex(ni);setPlaced(Array(puzzles[ni].slots.length).fill(null));setSelected(null);setChecked(false);setRevealed(false);setStartedAt(Date.now())}}} className="min-h-11 rounded-lg bg-primary px-5 py-2.5 font-semibold text-primary-foreground disabled:opacity-40">{!checked?"Check arrangement":valid?(index===puzzles.length-1?"See results":"Next puzzle"):"Try again"}</button></div>
 </section></SkillTrainerShell>
}
