import { useState } from "react";
import SkillTrainerShell,{ChoiceField,MistakeCausePrompt,ResultsCard,TrainerProgress} from "../components/skillTrainers/SkillTrainerShell";
import {ESTIMATION_QUESTIONS} from "../data/skillTrainerQuestions";
import {saveSkillAttempt,selectSkillItems} from "../lib/skillTrainerProgress";
import {useAuth} from "../hooks/useAuth";
import {useSkillTrainerRunLog} from "../hooks/useSkillTrainerRunLog";
const DESCRIPTION="Estimate the likely range and choose the fastest sound shortcut before seeing the exact value. The aim is controlled approximation, not guessing.";
export default function QrEstimationTrainerPage(){const{user}=useAuth();const[sessionId,setSessionId]=useState(()=>crypto.randomUUID()),[startedAt,setStartedAt]=useState(()=>Date.now());const logRun=useSkillTrainerRunLog("qr_estimation",sessionId);const[reviewMode,setReviewMode]=useState(()=>new URLSearchParams(window.location.search).get("review")==="1");const[questions,setQuestions]=useState(()=>selectSkillItems("qr_estimation",ESTIMATION_QUESTIONS,8,reviewMode,user?.id));const[index,setIndex]=useState(0),[range,setRange]=useState(""),[strategy,setStrategy]=useState(""),[revealed,setRevealed]=useState(false),[score,setScore]=useState(0),[done,setDone]=useState(false);const q=questions[index],points=Number(range===q.rangeAnswer)+Number(strategy===q.strategyAnswer);const restart=()=>{setReviewMode(false);setSessionId(crypto.randomUUID());setQuestions(selectSkillItems("qr_estimation",ESTIMATION_QUESTIONS,8,false,user?.id));setIndex(0);setRange("");setStrategy("");setRevealed(false);setScore(0);setDone(false);setStartedAt(Date.now())};
if(done)return <SkillTrainerShell title="QR Estimation & Elimination Trainer" description={DESCRIPTION} path="/ucat-qr-estimation-trainer" hubPath="/ucat-quantitative-reasoning-practice" hubLabel="Quantitative Reasoning" faqKey="qrEstimation"><ResultsCard score={score} total={questions.length*2} onRestart={restart}/></SkillTrainerShell>;
return <SkillTrainerShell title="QR Estimation & Elimination Trainer" description={DESCRIPTION} path="/ucat-qr-estimation-trainer" hubPath="/ucat-quantitative-reasoning-practice" hubLabel="Quantitative Reasoning" faqKey="qrEstimation"><TrainerProgress current={index} total={questions.length} score={score+(revealed?points:0)}/><section className="rounded-2xl border border-border bg-card p-5 shadow-card sm:p-8"><p className="text-sm text-muted-foreground">{q.context}</p><h2 className="my-5 text-center text-3xl font-bold tabular-nums text-foreground">{q.calculation}</h2><div className="space-y-4"><ChoiceField legend="1. Which range must contain the answer?" options={q.rangeOptions} value={range} answer={q.rangeAnswer} revealed={revealed} onChange={setRange}/><ChoiceField legend="2. Which shortcut is fastest and still reliable?" options={q.strategyOptions} value={strategy} answer={q.strategyAnswer} revealed={revealed} onChange={setStrategy}/></div>{revealed&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4" role="status"><p className="font-semibold text-emerald-950">Exact answer: {q.exactAnswer}</p><p className="mt-1 text-sm text-emerald-900">{q.explanation}</p></div>}{revealed&&(points)<2&&<MistakeCausePrompt key={q.id} trainerType="qr_estimation" sessionId={sessionId} itemId={q.id} userId={user?.id}/>}<div className="mt-5 flex justify-end"><button type="button" disabled={!range||!strategy} onClick={()=>{if(!revealed){void saveSkillAttempt("qr_estimation",{clientSessionId:sessionId,review:reviewMode,itemId:q.id,score:points,max:2,seconds:Math.round((Date.now()-startedAt)/1000),at:new Date().toISOString(),components:{range:range===q.rangeAnswer,strategy:strategy===q.strategyAnswer}},user?.id);logRun({correct:score+points,total:(index+1)*2,completed:index===questions.length-1});setRevealed(true);return}const next=score+points;setScore(next);if(index===questions.length-1)setDone(true);else{setIndex(i=>i+1);setRange("");setStrategy("");setRevealed(false);setStartedAt(Date.now())}}} className="min-h-11 rounded-lg bg-primary px-5 py-2.5 font-semibold text-primary-foreground disabled:opacity-40">{revealed?(index===questions.length-1?"See results":"Next estimate"):"Check estimate"}</button></div></section></SkillTrainerShell>}
