/**
 * Generates a SQL file to seed trainer_questions from the DM JSON bank.
 * Run: npx tsx scripts/generateDmSeedSql.ts > /tmp/dm_seed.sql
 * Then: npx supabase db query --linked -f /tmp/dm_seed.sql
 */

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

type OldRow = {
  id: string;
  trainer_type: "venn-logic" | "data-logic" | "argument-judge";
  difficulty: "easy" | "medium" | "hard";
  stem: string;
  question: string;
  options: Array<{ id: "A" | "B" | "C" | "D"; text: string; label?: string }>;
  correct_answer: "A" | "B" | "C" | "D";
  explanation: string;
  skill_tag: string;
  common_trap: string;
  optional_working_steps: string[] | null;
  is_active: boolean;
};

function escape(s: string): string {
  return s.replace(/'/g, "''");
}

function toOptionsRecord(options: OldRow["options"]): Record<string, string> {
  const r: Record<string, string> = {};
  for (const o of options) r[o.id] = o.text;
  return r;
}

const jsonPath = join(__dirname, "../supabase/seed/dm_trainer_questions.json");
const rows = JSON.parse(readFileSync(jsonPath, "utf8")) as OldRow[];

const lines: string[] = [
  "-- DM trainer questions → trainer_questions migration seed",
  "-- Auto-generated by scripts/generateDmSeedSql.ts",
  "",
  "INSERT INTO public.trainer_questions (",
  "  legacy_id, section, trainer_type, question_kind, status, difficulty,",
  "  skill_tag, stem, explanation, content, media,",
  "  quality_status, quality_notes, is_flagged, flag_count",
  ") VALUES",
];

const values = rows.map((q, i) => {
  const content = {
    question: q.question,
    options: toOptionsRecord(q.options),
    correctAnswer: q.correct_answer,
    commonTrap: q.common_trap,
    ...(q.optional_working_steps ? { workingSteps: q.optional_working_steps } : {}),
  };

  const status = q.is_active ? "active" : "draft";
  const contentJson = escape(JSON.stringify(content));
  const stemEsc = escape(q.stem);
  const explEsc = escape(q.explanation);
  const idEsc = escape(q.id);
  const skillEsc = escape(q.skill_tag);
  const sep = i < rows.length - 1 ? "," : ";";

  return (
    `  ('${idEsc}', 'dm', '${q.trainer_type}', 'mcq', '${status}', '${q.difficulty}',` +
    `\n   '${skillEsc}', '${stemEsc}', '${explEsc}',` +
    `\n   '${contentJson}'::jsonb, '[]'::jsonb,` +
    `\n   'pass', 'Migrated from local DM trainer bank.', false, 0)${sep}`
  );
});

lines.push(...values);
lines.push("");
lines.push(`-- Total: ${rows.length} rows`);

process.stdout.write(lines.join("\n"));
